POST  http://localhost:3000/list/add
Content-Type: application/json

{
    "title": "a",
    "task":"task for exempel 6",
    "username":"moshe"
}

###

DELETE   http://localhost:3000/list/6751e5be8d7db2305cc8c75d
Content-Type: application/json

###

PUT    http://localhost:3000/list/6752bb17c33c2a041ad05bae
Content-Type: application/json

{
    "completed": false
}

###

GET http://localhost:3000/user
Content-Type: application/json

###

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username":"moshe",
    "password": "123456"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"moshe",
    "password": "123456"
}

###

GET http://localhost:3000/user/info
Content-Type: application/json
Cookie:access_token=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzU1ODA0ODU2MGY1MTM0NzBhZTg4NDkiLCJpYXQiOjE3MzM2NjU5MTMsImV4cCI6MTczNjI1NzkxM30.o1hvGBqC7PCrknIYsAF0A0DJF8xwn-sYZJ7KHrSZkag; Path=/; HttpOnly; Secure; SameSite=None